[build]
target = "riscv32imac-unknown-none-elf"

[target.riscv32imac-unknown-none-elf]
rustflags = [
  "-C",
  "link-arg=-Tmemory.x",
  "-C",
  "link-arg=-Tlink.x",
  "--cfg",
  "cxx_experimental_no_alloc",
  "-C",
  "link-args=-lc",
]
